#!/bin/sh
# (c) polikuo 2024
# Typically called from /usr/local/bin/desktop.sh
# $ labwc_makemenu APPNAME
# ideally, this script should not be called by root
# however, it should be fine

. /etc/init.d/tc-functions

[ "$1" ] || exit 1
TCUSER=$(cat /etc/sysconfig/tcuser 2> /dev/null) || TCUSER="tc"
TCEMENU=/home/${TCUSER}/.config/labwc/menu.xml
OUTFILE=$(mktemp)
CACHE=$(mktemp)

unset ONDEMAND

if [ "$1" = "labwc" -o "$1" = "labwc-menu-generator" ]; then
  exit 0
fi

# Check for freedesktop item
FREEDESK="/usr/local/share/applications"

case $1 in
  tinycore-* ) SKIP=1;;
  havoc ) SKIP=1;;
  *~[0-9]* ) SKIP=1;;
esac

# exclude exact match
EXCLUDE=$(awk -v str="$1" '$0 == str ".desktop"' /home/${TCUSER}/.config/labwc/exclude)
if [ -n "$EXCLUDE" ]; then
  SKIP=1
fi

[ $SKIP ] && rm -f $OUTFILE $CACHE && exit 0

if [ -e "${FREEDESK}/${1}.desktop" ]; then
  if ! grep -i windowmanager "${FREEDESK}/${1}.desktop"; then
    if [ -e "${FREEDESK}/${1}~1.desktop" ]; then
      LIST=$(ls ${FREEDESK}/* |
        grep -E "/${1}(~[0-9][0-9]*)*\.desktop" |
        grep -Fvf /home/${TCUSER}/.config/labwc/exclude
      )
      if [ $(echo "$LIST" | wc -l) -gt 1 ]; then
        echo "<menu id=\"$1\" label=\"$1\"><!--labwc-->" > "$OUTFILE"
        for F in $LIST; do
          labwc_writeMenuItem "$F" >> "$OUTFILE"
        done
        echo "</menu><!--labwc-->" >> "$OUTFILE"
      else
        labwc_writeMenuItem $LIST > "$OUTFILE"
      fi
    else
      labwc_writeMenuItem "${FREEDESK}/${1}.desktop" > "$OUTFILE"
    fi
    labwc_append "$OUTFILE" "$TCEMENU" > "$CACHE"
    # use cat to prevent root from messing around the permission
    cat "$CACHE" > "$TCEMENU"
  fi
fi

rm -f $OUTFILE $CACHE

# Typically called by /usr/bin/tce-load
# This is just a fail safe
labwc_restart
